### ISSUE TITLE
forcing a float directly to integer creates rounding issues

### ISSUE THREAD

**Issue by BenjaminVerkleij** [jwiegant/laravel-tikkie#9]
When creating a payment. for example;

```
$tikkie->paymentRequest()->create(
                'My payment',
                12345,
                Carbon::now()->addDay(),
                19.90
            );
```

The method `$paymentRequestCreate->setAmountInCents($amount * 100)` will create `1990.0` as a value, which then in turn gets forced as an integer resulting in the amount `1989` instead of `1990`.

So a payment of € 19,90 will be turned into a payment of € 19,89.

A possible solution is to cast the amount in cents as a string before making it an integer;
`$cents = (int) ((string) ($amount * 100)); `

If the `$amount` variable is a `19.90` float, the `$cents` value will then still be `1990` instead of `1989`.

Or you could use the bcmul() method but that would require the BC Math php extension.

Thanks for creating this tikkie package! It makes tikkie implementation a breeze.

**Comment by jwiegant** [comment]
Thanks Benjamin, I'll look into it right away.

**Comment by jwiegant** [comment]
Hi @BenjaminVerkleij , 

I've fixed the problem and released a new version.

**Comment by BenjaminVerkleij** [comment]
Hi @jwiegant,

Thanks for the fast update, can confirm it's rounding correctly now.
